name: adasketch
channels:
- defaults
dependencies:
- python
- ipython
- numpy
- scipy
- pandas
- scikit-learn
- matplotlib
- seaborn
- pip
- pip:
    - pytest
    - pytest-cov
    - tox
    - -e .
    - pre-commit
