# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.0.2
      with:
        auto-update-conda: true
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@v2
    - name: Try getting started instructions
      shell: bash -l {0}
      run: |
        conda env create -f environment.yml
        conda activate adasketch
        python run_this.py
